### ISSUE TITLE
Incorrect Answer

### ISSUE THREAD

**Issue by ylnest2018** [Ditectrev/ITIL-4-Foundation-IT-Service-Management-Practice-Tests-Exams-Questions-Answers#1]
Which practice provides a single point of contact for users?
 Incident Management.
 Change Control.
 Service Desk.
 X Service Request Management.

The answer is Service Desk, I am not sure how many other's are wrong here but now I am unsure truly how well or bad I have gone, I even bought your Udemy course now I am second guessing that purchase.

**Comment by danieldanielecki** [comment]
> Which practice provides a single point of contact for users?
> 
>  Incident Management.
> 
>  Change Control.
> 
>  Service Desk.
> 
>  X Service Request Management.
> 
> 
> 
> The answer is Service Desk, I am not sure how many other's are wrong here but now I am unsure truly how well or bad I have gone, I even bought your Udemy course now I am second guessing that purchase.

Hey, I replied already on Udemy. Once again, feel free to request for a refund!

Fixed in https://github.com/Ditectrev/ITIL-4-Foundation-IT-Service-Management-Practice-Tests-Exams-Questions-Answers/commit/ec689a08f7bef455d5e5f00cf0f590ef23e76f16

**Comment by danieldanielecki** [comment]
@ylnest2018 I'm sad to see you're no longer a student over there, even though your Udemy comments were very enthusiastic :( Next time, kindly please leave a positive review if you're happy; it helps us to grow!
